apiVersion: apps/v1
kind: Deployment
metadata:
  name: ks-frontend
  labels:
    run: ks-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      project: k8s
      service: fundamentals
      version: "0.1" 
  template:
    metadata:
      name: ks-frontend
      labels:
        project: k8s
        service: fundamentals
        version: "0.1" 
    spec:
      containers:
      - name: react-app
        image: k8sf-front:latest
        imagePullPolicy: IfNotPresent
        tty: true
        ports:
        - containerPort: 3000
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
  minReadySeconds: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
---
kind: Service
apiVersion: v1
metadata:
  name: ks-frontend
  labels:
    project: k8s
    service: fundamentals
    version: "0.1" 
spec:
  type: NodePort
  selector:
    project: k8s
    service: fundamentals
    version: "0.1" 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
