echo "Set env vars"

export REACT_APP_POD_NAME=$POD_NAME
echo "REACT_APP_POD_NAME=$REACT_APP_POD_NAME"
echo "REACT_APP_POD_NAME=$REACT_APP_POD_NAME" >> .env_vars

export REACT_APP_POD_NAMESPACE=$POD_NAMESPACE
echo "REACT_APP_POD_NAMESPACE=$REACT_APP_POD_NAMESPACE"
echo "REACT_APP_POD_NAMESPACE=$REACT_APP_POD_NAMESPACE" >> .env_vars

export REACT_APP_POD_IP=$POD_IP
echo "REACT_APP_POD_IP=$REACT_APP_POD_IP"
echo "REACT_APP_POD_IP=$REACT_APP_POD_IP" >> .env_vars

export REACT_APP_NODE_NAME=$NODE_NAME
echo "REACT_APP_NODE_NAME=$REACT_APP_NODE_NAME"
echo "REACT_APP_NODE_NAME=$REACT_APP_NODE_NAME" >> .env_vars

export BROWSER="none"
echo "BROWSER=$BROWSER"
echo "BROWSER=$BROWSER" >> .env_vars


echo
echo "Run app"
npm start
